# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89474672304acc8adff2dbdabc584ad8b52b2ac945d9569e9d4b1c918e6bc29fdc6ccc18f3e561237b12b6a6fb1d55de47955e5bb8c7733a6c6e9ebe65622eff

test:
  secret_key_base: 3ac6aa5abe678898510212ad6cce30f573cfab75887ecc250c057841182dcb610c38e640bc2d1743eb340d1d6f9daa5d015d995571ab832912bb7d43e28e2057

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
